name: Report
on:
  schedule:
    - cron:  '00 15 * * *'
    - cron:  '00 15-17 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Report
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Once a day write data at 11h UTC
        run: |
          pip install -r requirements.txt
          python extract.py deploy
        if: github.event_name == 'schedule' && github.event.schedule == '00 15 * * *'
      - name: Every X hour write latest data
        run: |
          pip install -r requirements.txt
          python extract.py deploy latest
        if: github.event_name == 'schedule' && github.event.schedule != '00 15 * * *'
      - name: Commit report
        run: |
          git config --global user.name 'Bertrand Martel'
          git config --global user.email 'bertrandmartel@users.noreply.github.com'
          git add -A
          git checkout master
          git commit -am "Automated deploy"
          git push
